Project_63132986/Models/Employees_63132986.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project_63132986.Models
{
    public class Employees_63132986
    {
        public int ID { get; set; }
        public string EmployeeName { get; set; }
        public string DateOfBirth { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public bool Sex { get; set; }
        public string EmployeeAddress { get; set; }
        public string Avatar { get; set; }
        public string Position { get; set; }
        public string Salary { get; set; }

    }
}

Project_63132986/Controllers/Employees_63132986Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Project_63132986.Models;

namespace Project_63132986.Controllers
{
    public class Employees_63132986Controller : Controller
    {
        private Project_63132986Entities1 db = new Project_63132986Entities1();

        // GET: Employees_63132986
        public ActionResult Index()
        {
            return View();

        }

        // GET: Employees_63132986/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);

            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees_63132986/Create
        public ActionResult Create()
        {
            ViewBag.PositionID = new SelectList(db.Positions, "ID", "PositionName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,EmployeeName,DateOfBirth,Email,PhoneNumber,Sex,EmployeeAddress,PositionID,Avatar")] 
        Employee employee)
        {
            var Avatar = Request.Files["Avatar"];
            var path = "";
            string postedFileName = "";
            try
            {
                postedFileName = System.IO.Path.GetFileName(Avatar.FileName);
                path = Server.MapPath("~/assets/images/" + postedFileName);
                Avatar.SaveAs(path);
            }
            catch { }
            if (ModelState.IsValid)
            {
                employee.Avatar = postedFileName;
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PositionID = new SelectList(db.Positions, "ID", "PositionName", employee.PositionID);
            return View(employee);
        }

        // GET: Employees_63132986/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.PositionID = new SelectList(db.Positions, "ID", "PositionName", employee.PositionID);
            return View(employee);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,EmployeeName,DateOfBirth,Email,PhoneNumber,Sex," +
            "EmployeeAddress,PositionID,Avatar")] Employee employee)
        {
            var Avatar = Request.Files["Avatar"];
            Employee emp = db.Employees.Find(employee.ID);
            if (Avatar.ContentLength>0)
            {
                var path = "";
                string postedFileName = "";
                try
                {
                    postedFileName = System.IO.Path.GetFileName(Avatar.FileName);
                    path = Server.MapPath("~/assets/images/" + postedFileName);
                    Avatar.SaveAs(path);
                    emp.Avatar = postedFileName;
                }
                catch { }
            }
            if (ModelState.IsValid)
            {          
                emp.PhoneNumber = employee.PhoneNumber;
                emp.PositionID = employee.PositionID;
                emp.DateOfBirth = employee.DateOfBirth;
                emp.Email = employee.Email;
                emp.Sex = employee.Sex;
                emp.EmployeeName = employee.EmployeeName;
                emp.EmployeeAddress = employee.EmployeeAddress;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PositionID = new SelectList(db.Positions, "ID", "PositionName", employee.PositionID);
            return View(employee);
        }

        // GET: Employees_63132986/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var employee = db.Employees.Where(x => x.ID == id).FirstOrDefault();
            if (employee != null)
            {
                db.Employees.Remove(employee);
                db.SaveChanges();
                return Json(new { status = "success" }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { status = "unsuccess" }, JsonRequestBehavior.AllowGet);
        }


        // Get Employees List 
        public ActionResult GetList()
        {
            var employees = db.Employees.ToList();
            List<Employees_63132986> employeeList = new List<Employees_63132986>();
            employees.ForEach(e =>
                {
                    Employees_63132986 emp = new Employees_63132986();
                    emp.EmployeeName = e.EmployeeName;
                    emp.DateOfBirth = e.DateOfBirth.ToString("dd-MM-yyyy");
                    emp.Email = e.Email;
                    emp.EmployeeAddress = e.EmployeeAddress;
                    emp.Position = e.Position.PositionName;
                    emp.ID = e.ID;
                    emp.PhoneNumber = e.PhoneNumber;
                    emp.Sex = e.Sex;
                    employeeList.Add(emp);
                }
            );
            return Json(new { data = employeeList.ToList()}, JsonRequestBehavior.AllowGet);
        }
    }
}

Project_63132986/Views/Employees_63132986/Create.cshtml
@model Project_63132986.Models.Employee

@{
    ViewBag.Title = "Employees";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Employees</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Forms</a></div>
                <div class="breadcrumb-item">Employees</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Add Employee</h2>
            <p class="section-lead">We provide advanced input fields, such as date picker, color picker, and so on.</p>

            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Input Text</h4>
                        </div>
                        @using (Html.BeginForm("Create", "Employees_63132986", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="card-body">
                                @*Name*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.EmployeeName)
                                    @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
                                </div>
                                @*DOB*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.DateOfBirth)
                                    @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = " datepicker form-control" } })
                                    @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                                </div>
                                @*Phone Number*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">
                                                <i class="fas fa-phone"></i>
                                            </div>
                                        </div>
                                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "phone-number form-control" } })
                                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                @*Sex*@
                                <div class="form-group">
                                    <label>Sex</label>
                                    <select class="form-control">
                                        <option>Male</option>
                                        <option>Female</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                                </div>
                                @*Email*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Email)
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                                @*Address*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.EmployeeAddress, htmlAttributes: new { @class = "control-label" })

                                    @Html.EditorFor(model => model.EmployeeAddress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.EmployeeAddress, "", new { @class = "text-danger" })

                                </div>
                                @*Position*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PositionID, "PositionID", htmlAttributes: new { @class = "control-label" })

                                    @Html.DropDownList("PositionID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.PositionID, "", new { @class = "text-danger" })

                                </div>
                                @*Avatar*@
                                <div class="form-group">
                                    <label>Avatar</label>
                                    <input name="Avatar" type="file" class="form-control">
                                </div>
                                <div>
                                    <a href="/Employees_63132986/Index" style="width:70px" class="text-white btn btn-danger"><i class="bi bi-escape"></i></a>
                                    &emsp;<button class="btn btn-primary">Create</button>

                                </div>
                            </div>
                        }

                    </div>


                </div>

            </div>
        </div>
    </section>
</div>

Project_63132986/Views/Employees_63132986/Delete.cshtml
@model Project_63132986.Models.Employee

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avatar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.PositionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.PositionName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project_63132986/Views/Employees_63132986/Details.cshtml
@model Project_63132986.Models.Employee

@{
    ViewBag.Title = "Employees";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    string sex = "Male";
    if (Model.Sex == false)
    {
        sex = "Female";
    }
}

<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Employees </h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Forms</a></div>
                <div class="breadcrumb-item">Employees </div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Employees Detail Information</h2>
            <p class="section-lead">We provide advanced input fields, such as date picker, color picker, and so on.</p>
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <h4>Employee #@Html.DisplayFor(model => model.ID)</h4>
                            <div class="d-flex flex-wrap align-items-center gap-5">
                                <div>
                                    <img class="rounded-3" width="300" src="~/assets/images/@Html.DisplayFor(model => model.Avatar)" />
                                </div>
                                <div class="fs-5">
                                    <div>
                                        <div class="fw-bold">
                                            @Html.DisplayNameFor(model => model.EmployeeName):
                                        </div>

                                        <div>
                                            @Html.DisplayFor(model => model.EmployeeName)
                                        </div>
                                    </div>

                                    <div>
                                        <div class="fw-bold ">
                                            @Html.DisplayNameFor(model => model.DateOfBirth):
                                        </div>

                                        <div>
                                            @Html.DisplayFor(model => model.DateOfBirth):
                                        </div>
                                    </div>

                                    <div>
                                        <div class="fw-bold ">
                                            @Html.DisplayNameFor(model => model.Email):
                                        </div>

                                        <div>
                                            @Html.DisplayFor(model => model.Email)
                                        </div>
                                    </div>

                                    <div>
                                        <div class="fw-bold ">
                                            @Html.DisplayNameFor(model => model.PhoneNumber):
                                        </div>

                                        <div>
                                            @Html.DisplayFor(model => model.PhoneNumber)
                                        </div>
                                    </div>

                                    <div>
                                        <div class="fw-bold ">
                                            @Html.DisplayNameFor(model => model.Sex):
                                        </div>

                                        <div>
                                            @sex
                                        </div>

                                    </div>
                                    <div>
                                        <div class="fw-bold ">
                                            @Html.DisplayNameFor(model => model.EmployeeAddress):
                                        </div>

                                        <div>
                                            @Html.DisplayFor(model => model.EmployeeAddress)
                                        </div>
                                    </div>
                                    <div>
                                        <div class="fw-bold ">
                                            @Html.DisplayNameFor(model => model.Position.PositionName):
                                        </div>

                                        <div>
                                            @Html.DisplayFor(model => model.Position.PositionName)
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <hr style="opacity:0.1"/>
                            <div class="mt-5">
                                <a href="/Employees_63132986/Index" style="width:70px" class="text-white btn btn-danger"><i class="bi bi-escape"></i></a>
                                &emsp;<a href="/Employees_63132986/Edit/@Model.ID" style="width:70px" class="text-white btn btn-primary"><i class='bi bi-pencil-square'></i></a>
                            </div>
                        </div>
           
                    </div>
                </div>
                </div>

        </div>
    </section>
</div>

Project_63132986/Views/Employees_63132986/Edit.cshtml
@model Project_63132986.Models.Employee

@{
    ViewBag.Title = "Employees";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Employees</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-itemactive"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Forms</a></div>
                <div class="breadcrumb-item">Employees</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Edit Employee</h2>
            <p class="section-lead">We provideadvanced input fields, suchas date picker, color picker,and so on.</p>
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Input Text</h4>
                        </div>
                        <div class="card-body">
                            @using (Html.BeginForm("Edit", "Employees_63132986", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()

                                @*Name*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.EmployeeName)
                                    @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
                                </div>
                                @*DOB*@
                        <div class="form-group">
                            @Html.LabelFor(model => model.DateOfBirth)

                            <input value="@Model.DateOfBirth.ToString("yyyy-MM-dd")" name="DateOfBirth" type="text" class="datepicker form-control" />
                            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                        </div>
                                @*Phone Number*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">
                                                <i class="fas fa-phone"></i>
                                            </div>
                                        </div>
                                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "phone-number form-control" } })
                                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                @*Sex*@
                                <div class="form-group">
                                    <label>Sex</label>
                                    <select name="Sex" class="form-control">
                                        @{
                                            if (Model.Sex == true)
                                            {
                                                <option value="true" selected>Male</option>
                                                <option value="false">Female</option>
                                            }
                                            else
                                            {
                                                <option value="true" >Male</option>
                                                <option value="false" selected>Female</option>
                                            }
                                        }

                                    </select>
                                    @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                                </div>
                                @*Email*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Email)
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                                @*Address*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.EmployeeAddress, htmlAttributes: new { @class = "control-label" })

                                    @Html.EditorFor(model => model.EmployeeAddress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.EmployeeAddress, "", new { @class = "text-danger" })

                                </div>
                                @*Position*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PositionID, "PositionID", htmlAttributes: new { @class = "control-label" })

                                    @Html.DropDownList("PositionID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.PositionID, "", new { @class = "text-danger" })

                                </div>
                                <div class="form-group">

                                </div>
                                @*Avatar*@
                                <div class="form-group">
                                    <label>Avatar</label><br />
                                    <img class="rounded-3" width="300" src="~/assets/images/@Html.DisplayFor(model => model.Avatar)" />
                                    <br />      <br />
                                    <input value="empty" name="Avatar" type="file" class="form-control">
                                </div>
                                <div>
                                    <a href="/Employees_63132986/Index" style="width:70px" class="text-white btn btn-danger"><i class="bi bi-escape"></i></a>
                                    &emsp;<button class="btn btn-primary" style="width:70px"><i class="bi bi-check2-circle"></i></button>
                                </div>
                            }

                        </div>
                    </div>


                </div>

            </div>
        </div>
    </section>
</div>

Project_63132986/Views/Employees_63132986/Index.cshtml
@model IEnumerable<Project_63132986.Models.Employee>

@{
    ViewBag.Title = "Employees";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Employees</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Forms</a></div>
                <div class="breadcrumb-item">Employees</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Employees List</h2>
            <p class="section-lead">We provide advanced input fields, such as date picker, color picker, and so on.</p>

            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <a href="/Employees_63132986/Create" class="text-white btn btn-info my-3">Create</a>
                            <table id="userTable" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>DOB</th>
                                        <th>Phone Number</th>
                                        <th>Email</th>
                                        <th>Position</th>
                                        <th></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </section>
</div>

@section scripts{

    <script>

        $(document).ready(function () {
            $("#userTable").DataTable({
                "ajax": {
                    "url": "/Employees_63132986/GetList",
                    "type": "GET",
                    "data": "json"
                },
                "columns": [
                    { "data": "ID" },
                    { "data": "EmployeeName" },
                    { "data": "DateOfBirth" },
                    { "data": "PhoneNumber" },
                    { "data": "Email" },
                    { "data": "Position" },
                    {
                        "data": "ID", "class": "actionBtn text-center", "render": function (data) {
                            return "<a href ='/Employees_63132986/Details/" + data + "' class ='btn-update btn btn-info '><i class='bi bi-three-dots'></i></a><a href ='/Employees_63132986/Edit/"+data+"' class ='btn-update btn btn-primary mx-2'><i class='bi bi-pencil-square'></i></a><button data-id = '" + data + "' class = 'btn-delete btn btn-danger'><i class='bi bi-trash-fill'></i></button>";
                        },
                        "orderable": false,
                        "width": "200px",
                    }
                ]
            })
        })

        $("body").on("click",".btn-delete", function () {
            const id = $(this).data("id");
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        method: "POST",
                        url: "/Employees_63132986/Delete/" + id,
                        dataType: "JSON",
                        success: (data) => {

                            console.log($(this).parents("tr"));
                            $(this).parents("tr").hide();
                        },
                    });
                    Swal.fire({
                        title: "Deleted!",
                        text: "Your file has been deleted.",
                        icon: "success"
                    });

                }
            });


        })
    </script>
}