Project_63132986/Controllers/SliderBannerImages_63132986Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_63132986.Models;

namespace Project_63132986.Controllers
{
    public class SliderBannerImages_63132986Controller : Controller
    {
        private Project_63132986Entities1 db = new Project_63132986Entities1();

        // GET: SliderBannerImages_63132986
        public ActionResult Index()
        {
            return View(db.SliderBannerImages.ToList());
        }

        // GET: SliderBannerImages_63132986/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SliderBannerImage sliderBannerImage = db.SliderBannerImages.Find(id);
            if (sliderBannerImage == null)
            {
                return HttpNotFound();
            }
            return View(sliderBannerImage);
        }

        // GET: SliderBannerImages_63132986/Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase Image,SliderBannerImage bannerImage)
        {
            string postedFileName;
            postedFileName = System.IO.Path.GetFileName(Image.FileName);
            var path = Server.MapPath("~/assets/images/" + postedFileName);
            Image.SaveAs(path);
            bannerImage.BannerImage = postedFileName;
            db.SliderBannerImages.Add(bannerImage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: SliderBannerImages_63132986/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SliderBannerImage sliderBannerImage = db.SliderBannerImages.Find(id);
            if (sliderBannerImage == null)
            {
                return HttpNotFound();
            }
            return View(sliderBannerImage);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase Image,int ID, SliderBannerImage bannerImage)
        {
            var newBanner = db.SliderBannerImages.Find(ID);
            if (Image != null)
            {
                string postedFileName;
                postedFileName = System.IO.Path.GetFileName(Image.FileName);
                var path = Server.MapPath("~/assets/images/" + postedFileName);
                Image.SaveAs(path);
                newBanner.BannerImage = postedFileName;
             }
            if (ModelState.IsValid)
            {
                newBanner.ImageOrder = bannerImage.ImageOrder;
                newBanner.Link = bannerImage.Link;
                newBanner.Title = bannerImage.Title;
                newBanner.Content = bannerImage.Content;
     
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var sliderBannerImages = db.SliderBannerImages.Where(x => x.ID == id).FirstOrDefault();
            if (sliderBannerImages != null)
            {
                db.SliderBannerImages.Remove(sliderBannerImages);
                db.SaveChanges();
                return Json(new { status = "success", message = "Delete succesfully" }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { status = "unsuccess" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetList()
        {
            var Images = db.SliderBannerImages.ToList();
            return Json(new { data = Images }, JsonRequestBehavior.AllowGet);
        }
    }
}

Project_63132986/Views/SliderBannerImages_63132986/Create.cshtml
@model Project_63132986.Models.SliderBannerImage

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Slider Banner Images</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Forms</a></div>
                <div class="breadcrumb-item">Slider Banner Images</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Add Image Into Slider</h2>
            <p class="section-lead">We provide advanced input fields, such as date picker, color picker, and so on.</p>

            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Input Text</h4>
                        </div>
                        @using (Html.BeginForm("Create", "SliderBannerImages_63132986", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="card-body">
                                @*Image*@
                                <div class="form-group">
                                    <label>Banner Image</label>
                                    <input name="Image" type="file" class="form-control">
                                </div>
                                @*Title*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Title)
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                </div>
                                @*Content*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Content)
                                    @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                </div>
                                @*Link*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Link)
                                    @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
                                </div>
                                <div>
                                    <a href="/SliderBannerImages_63132986/Index/@ViewBag.ServiceID" style="width:70px" class="text-white btn btn-danger"><i class="bi bi-escape"></i></a>
                                    &emsp;<button class="btn btn-primary">Create</button>
                                </div>
                            </div>
                        }
                    </div>


                </div>

            </div>
        </div>
    </section>
</div>

Project_63132986/Views/SliderBannerImages_63132986/Delete.cshtml
@model Project_63132986.Models.SliderBannerImage

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SliderBannerImage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BannerImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BannerImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project_63132986/Views/SliderBannerImages_63132986/Details.cshtml
@model Project_63132986.Models.SliderBannerImage

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SliderBannerImage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BannerImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BannerImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project_63132986/Views/SliderBannerImages_63132986/Edit.cshtml
@model Project_63132986.Models.SliderBannerImage

@{
    ViewBag.Title = "SliderBanners";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Slider Banner Images</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-itemactive"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Forms</a></div>
                <div class="breadcrumb-item">Slider Banner Images</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Edit Slider Banner Image</h2>
            <p class="section-lead">We provideadvanced input fields, suchas date picker, color picker,and so on.</p>
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Input Text</h4>
                        </div>
                        @using (Html.BeginForm("Edit", "SliderBannerImages_63132986", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="card-body">
                                <input type="hidden" name="ID" value="@Model.ID" />
                                <div class="form-group">
                                    <img class="rounded" src="~/assets/images/@Model.BannerImage" width="250px" /><br /><br />
                                    <label>Banner Image</label>
                                    <input name="Image" type="file" class="form-control">
                                </div>

                                @*Title*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Title)
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                </div>
                                @*Content*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Content)
                                    @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                </div>
                                @*Link*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Link)
                                    @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
                                </div>
                                @*Order*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ImageOrder)
                                    @Html.EditorFor(model => model.ImageOrder, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ImageOrder, "", new { @class = "text-danger" })
                                </div>
                                <div>
                                    <a href="/SliderBannerImages_63132986/Index" style="width:70px" class="text-white btn btn-danger"><i class="bi bi-escape"></i></a>
                                    &emsp;<button class="btn btn-primary">Update</button>

                                </div>
                            </div>
                        }

                    </div>
                </div>


            </div>

        </div>

    </section>
</div>

Project_63132986/Views/SliderBannerImages_63132986/Index.cshtml
@model IEnumerable<Project_63132986.Models.SliderBannerImage>

@{
    ViewBag.Title = "SliderBanners";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Slider Banner Image</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Forms</a></div>
                <div class="breadcrumb-item">Slider Banner Image</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Slider Banner Image List</h2>
            <p class="section-lead">We provide advanced input fields, such as date picker, color picker, and so on.</p>

            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <a href="/SliderBannerImages_63132986/Create" class="text-white btn btn-info my-3">Create</a>
                            <table id="userTable" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Banner Images</th>
                                        <th>Title</th>
                                        <th>Content</th>
                                        <th>Link</th>
                                        <th></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </section>
</div>

@section scripts{

    <script>

        $(document).ready(function () {
            $("#userTable").DataTable({
                "ajax": {
                    "url": "/SliderBannerImages_63132986/GetList/@ViewBag.ServiceID",
                    "type": "GET",
                    "data": "json"
                },
                "columns": [
                    { "data": "ID" },
                    {
                        "data": "BannerImage", "render": function (data) {
                            return "<div class='text-center'><img class='rounded' style='object-fit:cover' height='200'width='300' src='/assets/images/" + data +"'/> </div>";
                        }
                    },
                    { "data": "Title", "width": "150px", "class": "overflow-auto"},
                    { "data": "Content", "width": "300px", "class": "overflow-auto"},
                    { "data": "Link", "width": "200px","class": "overflow-auto"},
                    {
                        "data": "ID", "class": "actionBtn text-center", "render": function (data) {
                            return "<a href ='/SliderBannerImages_63132986/Edit/" + data + "' class ='btn-update btn btn-primary mx-2'><i class='bi bi-pencil-square'></i></a><button data-id = '" + data + "' class = 'btn-delete btn btn-danger'><i class='bi bi-trash-fill'></i></button>";
                        },
                        "orderable": false,
                        "width": "100px",
                    }
                ]
            })
        })


        // Delete Room Types
        $("body").on("click",".btn-delete", function () {
            const id = $(this).data("id");
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        method: "POST",
                        url: "/SliderBannerImages_63132986/Delete/" + id,
                        dataType: "JSON",
                        success: (data) => {
                            if (data.status == "unsuccess") {
                                Swal.fire({
                                    title: "Cannot deleted",
                                    text: data.message,
                                    icon: "error"
                                });
                            }
                            else {
                                console.log($(this).parents("tr"));
                                $(this).parents("tr").hide();
                                Swal.fire({
                                    title: "Deleted!",
                                    text: data.message,
                                    icon: "success"
                                });
                            }
                        },
                    });
                    Swal.fire({
                        title: "Deleted!",
                        text: "Your file has been deleted.",
                        icon: "success"
                    });

                }
            });


        })
    </script>
}