Project_63132986/Controllers/ServiceImages_63132986Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_63132986.Models;

namespace Project_63132986.Controllers
{
    public class ServiceImages_63132986Controller : Controller
    {
        private Project_63132986Entities1 db = new Project_63132986Entities1();

        // GET: ServiceImages_63132986
        public ActionResult Index(int? ID)
        {
            if (ID != null) ViewBag.ServiceID = ID;
            return View();
        }

        // GET: ServiceImages_63132986/Create
        public ActionResult Create(int ID)
        {
            ViewBag.ServiceID = ID;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int ServiceID, HttpPostedFileBase Image)
        {
            string postedFileName;
            postedFileName = System.IO.Path.GetFileName(Image.FileName);
            var path = Server.MapPath("~/assets/images/" + postedFileName);
            Image.SaveAs(path);
            ServiceImage gallery = new ServiceImage();
            gallery.ServiceID = ServiceID;
            gallery.ServiceImage1 = postedFileName;
            db.ServiceImages.Add(gallery);
            db.SaveChanges();
            return RedirectToAction("Index/" + ServiceID);
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            var serviceImage = db.ServiceImages.Where(x => x.ID == id).FirstOrDefault();
            if (serviceImage != null)
            {
                db.ServiceImages.Remove(serviceImage);
                db.SaveChanges();
                return Json(new { status = "success", message = "Delete succesfully" }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { status = "unsuccess" }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult GetList(int id)
        {
            var Images = db.ServiceImages.
                Where(e => e.ServiceID == id).
                Select(e => new { e.ID, e.ServiceImage1, e.ServiceID }).
                ToList();
            return Json(new { data = Images }, JsonRequestBehavior.AllowGet);
        }
    }
}

Project_63132986/Views/ServiceImages_63132986/Create.cshtml
@model Project_63132986.Models.ServiceImage

@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Service Image Galleries</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Forms</a></div>
                <div class="breadcrumb-item">Service Image Galleries</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Add Image Into Service Image Gallery</h2>
            <p class="section-lead">We provide advanced input fields, such as date picker, color picker, and so on.</p>

            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Input Text</h4>
                        </div>
                        @using (Html.BeginForm("Create", "ServiceImages_63132986", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="card-body">
                                @*Image*@
                                <div class="form-group">

                                    <input value="@ViewBag.ServiceID" name="ServiceID" type="hidden" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label>Image</label>
                                    <input name="Image" type="file" class="form-control">
                                </div>
                                <div>
                                    <a href="/ServiceImages_63132986/Index/@ViewBag.ServiceID" style="width:70px" class="text-white btn btn-danger"><i class="bi bi-escape"></i></a>
                                    &emsp;<button class="btn btn-primary">Create</button>
                                </div>
                            </div>
                        }

                    </div>


                </div>

            </div>
        </div>
    </section>
</div>

Project_63132986/Views/ServiceImages_63132986/Delete.cshtml
@model Project_63132986.Models.ServiceImage

@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ServiceImage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ServiceImage1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceImage1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelService.ServiceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelService.ServiceName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project_63132986/Views/ServiceImages_63132986/Details.cshtml
@model Project_63132986.Models.ServiceImage

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ServiceImage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ServiceImage1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceImage1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelService.ServiceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelService.ServiceName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project_63132986/Views/ServiceImages_63132986/Edit.cshtml
@model Project_63132986.Models.ServiceImage

@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ServiceImage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceID, "ServiceID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ServiceID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceImage1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceImage1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceImage1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project_63132986/Views/ServiceImages_63132986/Index.cshtml
@model IEnumerable<Project_63132986.Models.ServiceImage>

@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Service Image Gallery</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Forms</a></div>
                <div class="breadcrumb-item">Service Image Gallery</div>
            </div>
        </div>

        <div class="section-body">
            <h2 class="section-title">Service Images Gallery</h2>
            <p class="section-lead">We provide advanced input fields, such as date picker, color picker, and so on.</p>

            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <a href="/HotelServices_63132986/Index" class=" text-white btn btn-danger my-3 mr-3"><i class="bi bi-escape"></i></a>
                            <a href="/ServiceImages_63132986/Create/@ViewBag.ServiceID" class="text-white btn btn-info my-3">Create</a>
                            <table id="userTable" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Service Images</th>
                                        <th></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </section>
</div>

@section scripts{

    <script>

        $(document).ready(function () {
            $("#userTable").DataTable({
                "ajax": {
                    "url": "/ServiceImages_63132986/GetList/@ViewBag.ServiceID",
                    "type": "GET",
                    "data": "json"
                },
                "columns": [
                    { "data": "ID" },
                    {
                        "data": "ServiceImage1", "render": function (data) {
                            return "<div class='text-center'><img style='object-fit:cover' height='200'width='500' src='/assets/images/" + data +"'/> </div>";
                        }
                    },
                    {
                        "data": "ID", "class": "actionBtn text-center", "render": function (data) {
                            return "<button data-id = '" + data + "' class = 'btn-delete btn btn-danger'><i class='bi bi-trash-fill'></i></button>";
                        },
                        "orderable": false,
                        "width": "200px",
                    }
                ]
            })
        })


        // Delete Room Types
        $("body").on("click",".btn-delete", function () {
            const id = $(this).data("id");
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        method: "POST",
                        url: "/ServiceImages_63132986/Delete/" + id,
                        dataType: "JSON",
                        success: (data) => {
                            if (data.status == "unsuccess") {
                                Swal.fire({
                                    title: "Cannot deleted",
                                    text: data.message,
                                    icon: "error"
                                });
                            }
                            else {
                                console.log($(this).parents("tr"));
                                $(this).parents("tr").hide();
                                Swal.fire({
                                    title: "Deleted!",
                                    text: data.message,
                                    icon: "success"
                                });
                            }
                        },
                    });
                    Swal.fire({
                        title: "Deleted!",
                        text: "Your file has been deleted.",
                        icon: "success"
                    });

                }
            });


        })
    </script>
}